version: '3'

services:
  selfhint: 
    container_name: selfhint
    image: node:14
    logging:
      options:
        max-size: "10k"
        max-file: "3"
    ports:
      - 8080:8080
    volumes:
      - ${PROJECT_HOME}:/usr/local/app/selfhint
    working_dir: /usr/local/app/selfhint/docker/scripts
    command: ./dev.sh